# Generated by Django 5.2.9 on 2025-12-23 08:15

import django.db.models.deletion
import django_extensions.db.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletterindexpage_alter_newsletterpage_body'),
        ('wagtail_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GothamNewsletterRecipient',
            fields=[
                ('newsletterrecipients_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtail_newsletter.newsletterrecipients')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'get_latest_by': 'modified',
            },
            bases=('wagtail_newsletter.newsletterrecipients',),
        ),
        migrations.AlterField(
            model_name='newsletterpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('button', 5)], block_lookup={0: ('newsletter.models.HeadingBlock', (), {}), 1: ('newsletter.models.RichParagraphBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.URLBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('url', 4)]], {})}),
        ),
        migrations.AlterField(
            model_name='newsletterpage',
            name='newsletter_recipients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.gothamnewsletterrecipient'),
        ),
        migrations.DeleteModel(
            name='NewsletterRecipient',
        ),
    ]
