# Generated by Django 5.2.9 on 2025-12-23 18:40

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_gothamnewsletterrecipient_alter_newsletterpage_body_and_more'),
        ('wagtail_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GothamSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'get_latest_by': 'created',
            },
        ),
        migrations.RemoveField(
            model_name='gothamnewsletterrecipient',
            name='newsletterrecipients_ptr',
        ),
        migrations.AlterField(
            model_name='newsletterpage',
            name='newsletter_recipients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtail_newsletter.newsletterrecipients'),
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.DeleteModel(
            name='GothamNewsletterRecipient',
        ),
    ]
