# Generated by Django 5.2.9 on 2026-01-27 19:48

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtailcache.cache
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cast', '0062_alter_transcript_options'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Age Group',
                'verbose_name_plural': 'Age Groups',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Fees Category',
                'verbose_name_plural': 'Fees Categories',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FocusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Focus/Topic',
                'verbose_name_plural': 'Focus/Topics',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenderFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Gender Filter',
                'verbose_name_plural': 'Gender Filters',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NYCNeighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'NYC Neighborhood',
                'verbose_name_plural': 'NYC Neighborhoods',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
            },
            bases=(wagtailcache.cache.WagtailCacheMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ProgramDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Program Delivery Method',
                'verbose_name_plural': 'Program Delivery Methods',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Location Type',
                'verbose_name_plural': 'Location Types',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Program Type',
                'verbose_name_plural': 'Program Types',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Selectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Program Selectivity',
                'verbose_name_plural': 'Program Selectivity',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Session Length',
                'verbose_name_plural': 'Session Lengths',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Session Start Month',
                'verbose_name_plural': 'Session Start Months',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditionsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Terms & Conditions',
            },
            bases=(wagtailcache.cache.WagtailCacheMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body_text', wagtail.fields.RichTextField(blank=True, max_length=2000)),
                ('founder_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'About',
            },
            bases=(wagtailcache.cache.WagtailCacheMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='GuidancePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_text', wagtail.fields.RichTextField(blank=True, max_length=500)),
                ('hero_description', wagtail.fields.RichTextField(blank=True, max_length=1000)),
                ('types_of_program', wagtail.fields.StreamField([('types_of_program', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "A unique ID for scrolling (e.g., 'subject-matter'). No spaces.", 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('nav_titile', 0), ('anchor_id', 1), ('content', 2)]], {})})),
                ('mathing_program', wagtail.fields.StreamField([('mathing_program', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "A unique ID for scrolling (e.g., 'subject-matter'). No spaces.", 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('nav_titile', 0), ('anchor_id', 1), ('content', 2)]], {})})),
                ('hero_image', models.ForeignKey(blank=True, help_text='The large background image for the hero section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'The Essentials',
            },
            bases=(wagtailcache.cache.WagtailCacheMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='home_homepage_pointer', serialize=False, to='wagtailcore.page')),
                ('hero_text', wagtail.fields.RichTextField(blank=True, max_length=500)),
                ('hero_description', wagtail.fields.RichTextField(blank=True, max_length=500)),
                ('intro_text', wagtail.fields.RichTextField(blank=True, max_length=1000)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Gotham Homepage',
            },
            bases=(wagtailcache.cache.WagtailCacheMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='HomePageFeaturedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_posts', to='home.homepage')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cast.post')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('accreditation', models.CharField(blank=True, help_text='Accrediting body name.', max_length=255, null=True)),
                ('application_details', models.CharField(blank=True, max_length=255, null=True)),
                ('application_selective', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Varies', 'Varies/N/A')], default='Varies', help_text='Is the application process highly selective?', max_length=10, null=True)),
                ('attached_files', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_private_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('contact_private_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('application_deadline', models.DateField(blank=True, help_text='application_deadline_date', null=True)),
                ('event_start_date', models.DateField(blank=True, help_text='For single-event programs, the start date.', null=True)),
                ('event_end_date', models.DateField(blank=True, help_text='For single-event programs, the end date.', null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('is_exceptional', models.BooleanField(default=False, help_text='exceptional_experience')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('press_links', models.CharField(blank=True, max_length=255, null=True)),
                ('my_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('program_overview', wagtail.fields.RichTextField(blank=True, help_text='Detailed description and program overview.', null=True)),
                ('program_summary', models.TextField(blank=True, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('scholarship_fin_aid', models.CharField(blank=True, max_length=255, null=True)),
                ('scholarship_fin_aid_details', models.CharField(blank=True, max_length=255, null=True)),
                ('years_in_business', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_details', models.TextField(blank=True, help_text='Brief details about the staff/founders.', null=True)),
                ('scholarship_details', models.TextField(blank=True, help_text='Details about scholarship or financial aid.', null=True)),
                ('gotham_state', models.CharField(choices=[('pending', 'Pending'), ('live', 'Llive'), ('archive', 'Archive')], default='pending', max_length=20)),
                ('logo_image', models.ForeignKey(blank=True, help_text="The provider's logo.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'program',
            },
            bases=(wagtailcache.cache.WagtailCacheMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ProgramAgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.agegroup')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_age_groups', to='home.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='age_groups',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='The age/school-level groups targeted (e.g., Middle School, High School).', through='home.ProgramAgeGroup', to='home.agegroup'),
        ),
        migrations.CreateModel(
            name='ProgramFeesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.feescategory')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_fees_categories', to='home.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='fees_category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='free_low_cost_program', through='home.ProgramFeesCategory', to='home.feescategory'),
        ),
        migrations.CreateModel(
            name='ProgramFocusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.focustopic')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_focus_topics', to='home.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='focus_topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='The STEM topics covered (e.g., Mathematics, Engineering).', through='home.ProgramFocusTopic', to='home.focustopic'),
        ),
        migrations.CreateModel(
            name='ProgramGenderFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.genderfilter')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_gender_filters', to='home.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='gender',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Who the program is for (e.g., Coed, Girls Only).', through='home.ProgramGenderFilter', to='home.genderfilter'),
        ),
        migrations.CreateModel(
            name='ProgramIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_text', wagtail.fields.RichTextField(blank=True, max_length=500)),
                ('hero_description', wagtail.fields.RichTextField(blank=True, max_length=1000)),
                ('hero_image', models.ForeignKey(blank=True, help_text='The large background image for the hero section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'programs',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramNYCNeighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.nycneighborhood')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_neighborhoods', to='home.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='nyc_neighborhood',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Specific NYC neighborhoods where the program takes place.', through='home.ProgramNYCNeighborhood', to='home.nycneighborhood'),
        ),
        migrations.CreateModel(
            name='ProgramProgramDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.programdelivery')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_delivery_methods', to='home.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='program_delivery',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='How the program is delivered (e.g., In-person, Online, Hybrid).', through='home.ProgramProgramDelivery', to='home.programdelivery'),
        ),
        migrations.CreateModel(
            name='ProgramProgramLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.programlocation')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_locations', to='home.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='locations',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='The geographical area of operation (e.g., NYC, Nationwide).', through='home.ProgramProgramLocation', to='home.programlocation'),
        ),
        migrations.CreateModel(
            name='ProgramProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_program_types', to='home.program')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.programtype')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='program_types',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='The general categories this program falls under (e.g., Class, Summer Day Camp).', through='home.ProgramProgramType', to='home.programtype'),
        ),
        migrations.CreateModel(
            name='ResourceAcademicStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('logo', models.ForeignKey(blank=True, help_text="The provider's logo.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Resource Category',
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('age_group', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('image', models.ForeignKey(blank=True, help_text='Resource Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='home.resourceacademicstage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceAcademicStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.resourceacademicstage')),
                ('resource', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_resource_categories', to='home.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('logo', models.ForeignKey(blank=True, help_text="The provider's logo.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Resource Type',
                'verbose_name_plural': 'Resource Types',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_resource_types', to='home.resource')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.resourcecategory')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='types',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.resourcecategory'),
        ),
        migrations.CreateModel(
            name='ResourceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_text', wagtail.fields.RichTextField(blank=True, max_length=500)),
                ('hero_description', wagtail.fields.RichTextField(blank=True, max_length=1000)),
                ('hero_image', models.ForeignKey(blank=True, help_text='The large background image for the hero section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'resource',
            },
            bases=(wagtailcache.cache.WagtailCacheMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ProgramSessionLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_session_lengths', to='home.program')),
                ('session_length', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.sessionlength')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='session_length',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, through='home.ProgramSessionLength', to='home.sessionlength'),
        ),
        migrations.CreateModel(
            name='ProgramSessionStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_session_starts', to='home.program')),
                ('session_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.sessionstart')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='session_start',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, through='home.ProgramSessionStart', to='home.sessionstart'),
        ),
    ]
