# Generated by Django 5.2.9 on 2025-12-18 19:25

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Age Group',
                'verbose_name_plural': 'Age Groups',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FeesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Fees Category',
                'verbose_name_plural': 'Fees Categories',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FocusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Focus/Topic',
                'verbose_name_plural': 'Focus/Topics',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenderFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Gender Filter',
                'verbose_name_plural': 'Gender Filters',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsightsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Insights',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NYCNeighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'NYC Neighborhood',
                'verbose_name_plural': 'NYC Neighborhoods',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('raw_html', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'strikethrough', 'superscript', 'subscript', 'blockquote', 'code', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'styles', 'colour']}), 1: ('home.utilities.RawHTMLBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Program Delivery Method',
                'verbose_name_plural': 'Program Delivery Methods',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Location Type',
                'verbose_name_plural': 'Location Types',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Program Type',
                'verbose_name_plural': 'Program Types',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Selectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Program Selectivity',
                'verbose_name_plural': 'Program Selectivity',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Session Length',
                'verbose_name_plural': 'Session Lengths',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Session Start Month',
                'verbose_name_plural': 'Session Start Months',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermsAndServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('raw_html', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'strikethrough', 'superscript', 'subscript', 'blockquote', 'code', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'styles', 'colour']}), 1: ('home.utilities.RawHTMLBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InsightsArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('image', 1), ('heading', 2), ('quote', 3), ('raw_html', 4)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'strikethrough', 'superscript', 'subscript', 'blockquote', 'code', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'styles', 'colour']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {}), 4: ('home.utilities.RawHTMLBlock', (), {})})),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='home_homepage_pointer', serialize=False, to='wagtailcore.page')),
                ('hero_text', wagtail.fields.RichTextField(blank=True, max_length=500)),
                ('body', wagtail.fields.StreamField([('feature_block', 10)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 150, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'strikethrough', 'superscript', 'subscript', 'blockquote', 'code', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'styles', 'colour'], 'help_text': 'Detailed text content for the feature section.', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Text for the call-to-action button (e.g., 'Explore Now')", 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Target page for the CTA button.', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('side-by-side-right', 'Image Right, Text Left'), ('side-by-side-left', 'Image Left, Text Right'), ('stacked-center', 'Image Top, Text Centered Bottom')], 'help_text': 'Choose the arrangement of the image and text.'}), 6: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'help_text': 'Optional: Set a custom background color for this block.', 'required': False}), 7: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'help_text': 'Optional: Set a custom text color for this block.', 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('start', 'Left (Start)'), ('end', 'Right (End)'), ('center', 'Center')], 'help_text': 'Horizontal alignment for the text content.', 'label': 'Text Alignment', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'Default Line Height (lh-base)'), ('lh-1', 'No extra leading (Single)'), ('lh-sm', 'Small Line Height'), ('lh-lg', 'Large Line Height (Double)')], 'help_text': 'Bootstrap line height utility class for text spacing.', 'label': 'Line Height', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('link_text', 3), ('link_page', 4), ('layout_style', 5), ('background_color', 6), ('text_color', 7), ('text_alignment', 8), ('line_height', 9)]], {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('featured_blogs', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select up to 3 articles to feature.', to='home.insightsarticlepage')),
            ],
            options={
                'verbose_name': 'Gotham Homepage',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('accreditation', models.CharField(blank=True, help_text='Accrediting body name.', max_length=255, null=True)),
                ('application_details', models.CharField(blank=True, max_length=255, null=True)),
                ('application_selective', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Varies', 'Varies/N/A')], default='Varies', help_text='Is the application process highly selective?', max_length=10, null=True)),
                ('attached_files', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_private_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('contact_private_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('application_deadline', models.DateField(blank=True, help_text='application_deadline_date', null=True)),
                ('event_start_date', models.DateField(blank=True, help_text='For single-event programs, the start date.', null=True)),
                ('event_end_date', models.DateField(blank=True, help_text='For single-event programs, the end date.', null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('is_exceptional', models.BooleanField(default=False, help_text='exceptional_experience')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('press_links', models.CharField(blank=True, max_length=255, null=True)),
                ('my_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('program_overview', wagtail.fields.RichTextField(blank=True, help_text='Detailed description and program overview.', null=True)),
                ('program_summary', models.TextField(blank=True, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('scholarship_fin_aid', models.CharField(blank=True, max_length=255, null=True)),
                ('scholarship_fin_aid_details', models.CharField(blank=True, max_length=255, null=True)),
                ('years_in_business', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_details', models.TextField(blank=True, help_text='Brief details about the staff/founders.', null=True)),
                ('scholarship_details', models.TextField(blank=True, help_text='Details about scholarship or financial aid.', null=True)),
                ('logo_image', models.ForeignKey(blank=True, help_text="The provider's logo.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'program',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramAgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.agegroup')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_age_groups', to='home.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='age_groups',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='The age/school-level groups targeted (e.g., Middle School, High School).', through='home.ProgramAgeGroup', to='home.agegroup'),
        ),
        migrations.CreateModel(
            name='ProgramFeesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.feescategory')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_fees_categories', to='home.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='fees_category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='free_low_cost_program', through='home.ProgramFeesCategory', to='home.feescategory'),
        ),
        migrations.CreateModel(
            name='ProgramFocusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.focustopic')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_focus_topics', to='home.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='focus_topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='The STEM topics covered (e.g., Mathematics, Engineering).', through='home.ProgramFocusTopic', to='home.focustopic'),
        ),
        migrations.CreateModel(
            name='ProgramGenderFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.genderfilter')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_gender_filters', to='home.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='gender',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Who the program is for (e.g., Coed, Girls Only).', through='home.ProgramGenderFilter', to='home.genderfilter'),
        ),
        migrations.CreateModel(
            name='ProgramIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.StreamField([('intro_block', 5), ('raw_html', 6)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'strikethrough', 'superscript', 'subscript', 'blockquote', 'code', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'styles', 'colour'], 'help_text': "Text content displayed next to the image. Supports standard formatting and color via the 'colour' feature.", 'required': True}), 1: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'default': '#C9BDEC'}), 2: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'default': '#000000'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'Default Line Height (lh-base)'), ('lh-1', 'No extra leading (Single)'), ('lh-sm', 'Small Line Height'), ('lh-lg', 'Large Line Height (Double)')], 'help_text': 'Select the line spacing for the text in this block.', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('start', 'Left (Start)'), ('end', 'Right (End)'), ('center', 'Center')], 'help_text': 'Choose the alignment of the text content (Left/Right/Center).'}), 5: ('wagtail.blocks.StructBlock', [[('text_left', 0), ('text_right', 0), ('background_color', 1), ('text_color', 2), ('line_height_class', 3), ('text_alignment', 4)]], {}), 6: ('home.utilities.RawHTMLBlock', (), {})}, help_text='Add alternating feature blocks (image and text) or raw HTML for the main body of the homepage.', null=True)),
                ('hero_image', models.ForeignKey(blank=True, help_text='The large background image for the hero section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'programs',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramNYCNeighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.nycneighborhood')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_neighborhoods', to='home.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='nyc_neighborhood',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Specific NYC neighborhoods where the program takes place.', through='home.ProgramNYCNeighborhood', to='home.nycneighborhood'),
        ),
        migrations.CreateModel(
            name='ProgramProgramDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.programdelivery')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_delivery_methods', to='home.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='program_delivery',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='How the program is delivered (e.g., In-person, Online, Hybrid).', through='home.ProgramProgramDelivery', to='home.programdelivery'),
        ),
        migrations.CreateModel(
            name='ProgramProgramLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.programlocation')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_locations', to='home.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='locations',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='The geographical area of operation (e.g., NYC, Nationwide).', through='home.ProgramProgramLocation', to='home.programlocation'),
        ),
        migrations.CreateModel(
            name='ProgramTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='home.program')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_program_types', to='home.program')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.programtype')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='program_types',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='The general categories this program falls under (e.g., Class, Summer Day Camp).', through='home.ProgramProgramType', to='home.programtype'),
        ),
        migrations.CreateModel(
            name='ProgramSessionLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_session_lengths', to='home.program')),
                ('session_length', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.sessionlength')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='session_length',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, through='home.ProgramSessionLength', to='home.sessionlength'),
        ),
        migrations.CreateModel(
            name='ProgramSessionStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_session_starts', to='home.program')),
                ('session_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.sessionstart')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='session_start',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, through='home.ProgramSessionStart', to='home.sessionstart'),
        ),
    ]
