# Generated by Django 5.2.9 on 2025-12-18 20:15

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0063_alter_audio_id_alter_chaptermark_id_alter_file_id_and_more'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insightsindexpage',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_blogs',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select up to 3 articles to feature.', to='cast.post'),
        ),
        migrations.DeleteModel(
            name='InsightsArticlePage',
        ),
        migrations.DeleteModel(
            name='InsightsIndexPage',
        ),
    ]
