# Generated by Django 5.2.9 on 2025-12-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunityindexpage',
            options={'verbose_name': 'programs'},
        ),
        migrations.AlterModelOptions(
            name='opportunitypage',
            options={'verbose_name': 'program'},
        ),
    ]
