# Generated by Django 5.2.9 on 2026-01-27 13:34

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAcademicStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('logo', models.ForeignKey(blank=True, help_text="The provider's logo.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Resource Category',
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('age_group', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('image', models.ForeignKey(blank=True, help_text='Resource Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='home.resourceacademicstage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceAcademicStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.resourceacademicstage')),
                ('resource', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_resource_categories', to='home.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('logo', models.ForeignKey(blank=True, help_text="The provider's logo.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Resource Type',
                'verbose_name_plural': 'Resource Types',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_resource_types', to='home.resource')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.resourcecategory')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='types',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.resourcecategory'),
        ),
    ]
