# Generated by Django 5.2.9 on 2026-01-28 11:17

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='academic_stages',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='resource_academic_stages', to='home.resourceacademicstage'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='resource_categories', to='home.resourceacademicstage'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='types',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='resources', to='home.resourcecategory'),
        ),
    ]
