# Generated by Django 5.2.9 on 2026-01-28 11:29

import django.db.models.deletion
import wagtailcache.cache
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_resource_academic_stages_alter_resource_categories_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceSearchResultPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'resource search results',
            },
            bases=(wagtailcache.cache.WagtailCacheMixin, 'wagtailcore.page'),
        ),
    ]
