# Generated by Django 5.2.9 on 2025-12-22 07:08

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_insightsindexpage_page_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='gotham_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('live', 'Llive'), ('archive', 'Archive')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('feature_block', 10)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 150, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Detailed text content for the feature section.', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Text for the call-to-action button (e.g., 'Explore Now')", 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Target page for the CTA button.', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('side-by-side-right', 'Image Right, Text Left'), ('side-by-side-left', 'Image Left, Text Right'), ('stacked-center', 'Image Top, Text Centered Bottom')], 'help_text': 'Choose the arrangement of the image and text.'}), 6: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'help_text': 'Optional: Set a custom background color for this block.', 'required': False}), 7: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'help_text': 'Optional: Set a custom text color for this block.', 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('start', 'Left (Start)'), ('end', 'Right (End)'), ('center', 'Center')], 'help_text': 'Horizontal alignment for the text content.', 'label': 'Text Alignment', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'Default Line Height (lh-base)'), ('lh-1', 'No extra leading (Single)'), ('lh-sm', 'Small Line Height'), ('lh-lg', 'Large Line Height (Double)')], 'help_text': 'Bootstrap line height utility class for text spacing.', 'label': 'Line Height', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('link_text', 3), ('link_page', 4), ('layout_style', 5), ('background_color', 6), ('text_color', 7), ('text_alignment', 8), ('line_height', 9)]], {})}),
        ),
        migrations.AlterField(
            model_name='privacypolicypage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('raw_html', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('home.utilities.RawHTMLBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='programindexpage',
            name='intro',
            field=wagtail.fields.StreamField([('intro_block', 5), ('raw_html', 6)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': "Text content displayed next to the image. Supports standard formatting and color via the 'colour' feature.", 'required': True}), 1: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'default': '#C9BDEC'}), 2: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'default': '#000000'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'Default Line Height (lh-base)'), ('lh-1', 'No extra leading (Single)'), ('lh-sm', 'Small Line Height'), ('lh-lg', 'Large Line Height (Double)')], 'help_text': 'Select the line spacing for the text in this block.', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('start', 'Left (Start)'), ('end', 'Right (End)'), ('center', 'Center')], 'help_text': 'Choose the alignment of the text content (Left/Right/Center).'}), 5: ('wagtail.blocks.StructBlock', [[('text_left', 0), ('text_right', 0), ('background_color', 1), ('text_color', 2), ('line_height_class', 3), ('text_alignment', 4)]], {}), 6: ('home.utilities.RawHTMLBlock', (), {})}, help_text='Add alternating feature blocks (image and text) or raw HTML for the main body of the homepage.', null=True),
        ),
        migrations.AlterField(
            model_name='termsandservicespage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('raw_html', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('home.utilities.RawHTMLBlock', (), {})}),
        ),
        migrations.DeleteModel(
            name='ProgramTag',
        ),
    ]
