# Generated by Django 5.2.9 on 2025-12-25 11:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_homepage_featured_blogs_homepagefeaturedpost'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidancePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', wagtail.fields.RichTextField(blank=True, max_length=500)),
                ('intro_text', wagtail.fields.RichTextField(blank=True, max_length=500)),
                ('hero_image', models.ForeignKey(blank=True, help_text='The large background image for the hero section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
