# Generated by Django 5.2.9 on 2025-12-18 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_wagtailpagelinks'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagtailpagelinks',
            name='about_page',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type__model': 'aboutpage'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
