# Generated by Django 5.2.9 on 2025-12-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_guidancepage_delete_contactpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guidancepage',
            options={'verbose_name': 'Guidance'},
        ),
    ]
