# Generated by Django 5.2.9 on 2025-12-25 13:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_guidancepage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancepage',
            name='sections',
            field=wagtail.fields.StreamField([('section', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "A unique ID for scrolling (e.g., 'subject-matter'). No spaces.", 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('anchor_id', 1), ('content', 2)]], {})}),
        ),
    ]
