# Generated by Django 5.2.9 on 2025-12-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_wagtailpagelinks_about_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WagtailPageLinks',
        ),
    ]
