# Generated by Django 5.2.9 on 2025-12-25 13:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_guidancepage_sections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidancepage',
            name='mathing_program',
            field=wagtail.fields.StreamField([('mathing_program', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "A unique ID for scrolling (e.g., 'subject-matter'). No spaces.", 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('nav_titile', 0), ('anchor_id', 1), ('content', 2)]], {})}),
        ),
        migrations.AlterField(
            model_name='guidancepage',
            name='types_of_program',
            field=wagtail.fields.StreamField([('types_of_program', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "A unique ID for scrolling (e.g., 'subject-matter'). No spaces.", 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('nav_titile', 0), ('anchor_id', 1), ('content', 2)]], {})}),
        ),
    ]
