# Generated by Django 5.2.9 on 2025-12-25 14:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_aboutpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='body_text',
            field=wagtail.fields.RichTextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='founder_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
