# Generated by Django 5.2.9 on 2025-12-25 14:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_aboutpage_body_text_aboutpage_founder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body_text',
            field=wagtail.fields.RichTextField(blank=True, max_length=2000),
        ),
    ]
