# Generated by Django 5.2.9 on 2025-12-25 15:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_aboutpage_body_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicypage',
            options={'verbose_name': 'Privacy Policy'},
        ),
        migrations.RemoveField(
            model_name='privacypolicypage',
            name='body',
        ),
        migrations.AddField(
            model_name='privacypolicypage',
            name='body_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
