# Generated by Django 5.2.9 on 2025-12-25 15:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_privacypolicypage_options_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditionsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Terms & Conditions',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='TermsAndServicesPage',
        ),
    ]
