# Generated by Django 5.2.9 on 2025-12-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_resource_resourcecategory_resourcepage_resourcetype_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='logo',
            field=models.ForeignKey(blank=True, help_text="The provider's logo.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
