# Generated by Django 5.2.9 on 2025-12-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_resourcecategory_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='age_group',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
