# Generated by Django 5.2.9 on 2026-01-26 10:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_resource_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=wagtail.fields.RichTextField(blank=True, max_length=500),
        ),
    ]
