# Generated by Django 5.2.9 on 2026-01-27 05:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_homepage_body_homepage_intro_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programindexpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='programindexpage',
            name='hero_description',
            field=wagtail.fields.RichTextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='programindexpage',
            name='hero_text',
            field=wagtail.fields.RichTextField(blank=True, max_length=500),
        ),
    ]
