# Generated by Django 5.2.9 on 2026-01-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_programindexpage_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='exceptional',
            field=models.BooleanField(default=False, help_text='Is the program Exceptional?'),
        ),
    ]
