# Generated by Django 5.2.9 on 2026-01-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_program_exceptional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='exceptional',
        ),
    ]
