# Generated by Django 5.2.9 on 2026-01-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_program_exceptional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guidancepage',
            options={'verbose_name': 'The Essentials'},
        ),
    ]
