# Generated by Django 5.2.9 on 2026-01-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_guidancepage_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guidancepage',
            old_name='intro_text',
            new_name='hero_text',
        ),
        migrations.RenameField(
            model_name='guidancepage',
            old_name='intro_title',
            new_name='hero_title',
        ),
    ]
