# Generated by Django 5.2.9 on 2026-01-27 09:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_intro_text_guidancepage_hero_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidancepage',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='guidancepage',
            name='hero_description',
            field=wagtail.fields.RichTextField(blank=True, max_length=1000),
        ),
    ]
