"""
Django settings for gotham_stem project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/#dat
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from pathlib import Path
import configparser
import os 
from cast import CAST_APPS, CAST_MIDDLEWARE

PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent
SITE_ID = 1
DEBUG_LEVEL = 'INFO'
ENV = 'local'
try:
    config = configparser.SafeConfigParser(allow_no_value=True)
except:
    #Python 3.12
    config = configparser.ConfigParser(allow_no_value=True)



# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

config.read(os.path.join(BASE_DIR, 'gotham_stem', 'settings', 'settings.cfg'))

def get_config_value(group, key, default=None):
    value = None
    try:
        value = config.get(group, key)
    except Exception as e:
        value = os.environ.get(f"{group.upper()}_{key.upper()}")
    if not value and default:
        value = default

    return value

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Application definition

INSTALLED_APPS = list(set([
    "home",
    "search",
    "newsletter",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.sitemaps",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required for RSS/Podcasts
    "django.contrib.sitemaps",
    "wagtail_modeladmin",
    "wagtail_color_panel",
    "wagtail_newsletter",
    "wagtailcache",
    # Required allauth apps
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
] + CAST_APPS))

MIDDLEWARE = [
    'wagtailcache.cache.UpdateCacheMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
] + CAST_MIDDLEWARE

MIDDLEWARE = MIDDLEWARE + ['wagtailcache.cache.FetchFromCacheMiddleware']

ROOT_URLCONF = "gotham_stem.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            PROJECT_DIR / "templates",
            PROJECT_DIR / "newsletter" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'wagtail.contrib.settings.context_processors.settings',
                "home.context_processors.site_info",
            ],
        },
    },
]


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": os.path.join(BASE_DIR, "cache"),
        "TIMEOUT": 3600, # 1 hour
    }
}

WSGI_APPLICATION = "gotham_stem.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': get_config_value('database', 'name'),
        'USER': get_config_value('database', 'user'),
        'PASSWORD': get_config_value('database', 'password'),
        'HOST': get_config_value('database', 'host'),
        'PORT': get_config_value('database', 'port')
    }
}

OCI = {
    'ACCESS_KEY' : get_config_value('oci','access_key'),
    'SECRET_KEY' : get_config_value('oci','secret_key'),
    'NAMESPACE' : get_config_value('oci','namespace'),
    'REGION' : get_config_value('oci','region'),
    'BUCKET_NAME' : get_config_value('oci','bucket'),
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


CAST_IMAGE_FORMATS = ["jpeg", "avif"]
CAST_BOOTSTRAP_VERSION = 4
CAST_COMMENTS_ENABLED = False
POST_LIST_PAGINATION = 9
CAST_REPOSITORY = True
CAST_THUMBNAIL_SLOT_DIMENSIONS = (340,240)
# Default storage settings
# See https://docs.djangoproject.com/en/6.0/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# Wagtail settings

WAGTAIL_SITE_NAME = "gotham_stem"

# --- WAGTAIL RICH TEXT EDITOR CONFIGURATION ---
WAGTAILADMIN_RICH_TEXT_EDITORS = {
    "default": {
        "WIDGET": "wagtail.admin.rich_text.DraftailRichTextArea",
        "OPTIONS": {
            "features": [
                # Headings and basic formatting
                "h1", "h2", "h3", "h4", "h5", "h6", 
                "bold", "italic", "strikethrough", "superscript", "subscript",
                
                # Lists, code, blockquotes, and dividers
                "ol", "ul", "code", "blockquote", "hr", 
                
                # Links and embedding
                "link", "document-link", "embed", "image", 

            ],
            # Custom Style Definitions (These correspond to CSS classes you must define in your static files)
            # This is how you provide "font selection" and "line spacing" control to the user:
            "entity_features": {
                "styles": {
                    "inline": [
                        {"label": "Subtle Emphasis", "type": "SMALL", "element": "span", "class": "text-muted"},
                        {"label": "Large Highlight", "type": "HIGHLIGHT", "element": "span", "class": "text-primary"},
                        # Use classes like these in your CSS to control line spacing/fonts
                        {"label": "Wide Line Spacing", "type": "WIDE_SPACE", "element": "span", "class": "line-height-lg"},
                        {"label": "Narrow Line Spacing", "type": "NARROW_SPACE", "element": "span", "class": "line-height-sm"},
                    ],
                    "block": [
                        {"label": "Callout Block", "type": "CALLOUT", "element": "div", "class": "callout-block"},
                        {"label": "Quote Source", "type": "SOURCE", "element": "cite"},
                    ],
                }
            }
        },
    }
}
# ---------------------------------------------------


# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}


# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
BASE_URL = WAGTAILADMIN_BASE_URL = "http://localhost:8000"
STATIC_URL = "/static/"

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "static"
MEDIA_ROOT = BASE_DIR / "media"

# WAGTAILIMAGES_IMAGE_MODEL = "cast.Image"

DJANGO_VITE_DEV_MODE = True

DJANGO_VITE = {
    "default": {
        "dev_mode": True,
    },
    "cast": {
        "dev_mode": True,
        # This tells Vite where to find the blog's specific manifest file
        "manifest_path": os.path.join(STATIC_ROOT, "cast", "vite", "manifest.json"),
        "static_url_prefix": "cast/",
    }
}


# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']


MAILCHIMP_API_KEY =  get_config_value('mailchimp','api_key')
MAILCHIMP_SERVER =  get_config_value('mailchimp','server')
MAILCHIMP_AUDIENCE_ID =  get_config_value('mailchimp','audience_id')

WAGTAIL_NEWSLETTER_MAILCHIMP_API_KEY = MAILCHIMP_API_KEY
WAGTAIL_NEWSLETTER_FROM_NAME = get_config_value('newsletter','from_name')
WAGTAIL_NEWSLETTER_REPLY_TO = get_config_value('newsletter','reply_to')
WAGTAIL_NEWSLETTER_CACHE_TIMEOUT = 3600
WAGTAIL_NEWSLETTER_CAMPAIGN_BACKEND = "wagtail_newsletter.campaign_backends.mailchimp.MailchimpCampaignBackend"
WAGTAIL_NEWSLETTER_RECIPIENTS_MODEL = "wagtail_newsletter.NewsletterRecipients"


NEWSLETTER_UTM_DEFAULTS = {
    "utm_source": "newsletter",
    "utm_medium": "email",
}


RECAPTCHA_SITE_KEY = get_config_value('google','recaptcha_site_key')
GOOGLE_API_KEY = get_config_value('google','api_key')
GOOGLE_PROJECT_ID = get_config_value('google','project_id')